config/routes.rb
Rails.application.routes.draw do
  resources :empleados
  resources :sucursals
  devise_for :users
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
  belongs_to :sucursal
end

app/models/sucursal.rb
class Sucursal < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @sucursals = Sucursal.where(user_id: current_user.id )
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
    @sucursals = Sucursal.where(user_id: current_user.id )
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)
    @sucursals = Sucursal.where(user_id: current_user.id )
    respond_to do |format|
      if @empleado.save
        format.html { redirect_to :home_index}
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to :home_index}
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre_completo, :RFC, :puesto, :sucursal_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @sucursals = Sucursal.where(user_id: current_user.id )
    @empleados = Empleado.all
  end
end

app/controllers/sucursals_controller.rb
class SucursalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sucursal, only: [:show, :edit, :update, :destroy]

  # GET /sucursals
  # GET /sucursals.json
  def index
    @sucursals = Sucursal.where(user_id: current_user.id )
  end

  # GET /sucursals/1
  # GET /sucursals/1.json
  def show
  end

  # GET /sucursals/new
  def new
    @sucursal = Sucursal.new
  end

  # GET /sucursals/1/edit
  def edit
    @empleados = Empleado.where(sucursal: @sucursal )
  end

  # POST /sucursals
  # POST /sucursals.json
  def create
    @sucursal = Sucursal.new(sucursal_params)
    @sucursal.user_id = current_user.id  
    respond_to do |format|
      if @sucursal.save
        format.html { redirect_to :home_index}
        format.json { render :show, status: :created, location: @sucursal }
      else
        format.html { render :new }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sucursals/1
  # PATCH/PUT /sucursals/1.json
  def update
    respond_to do |format|
      if @sucursal.update(sucursal_params)
        format.html { redirect_to :home_index}
        format.json { render :show, status: :ok, location: @sucursal }
      else
        format.html { render :edit }
        format.json { render json: @sucursal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sucursals/1
  # DELETE /sucursals/1.json
  def destroy
    @sucursal.destroy
    respond_to do |format|
      format.html { redirect_to sucursals_url, notice: 'Sucursal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sucursal
      @sucursal = Sucursal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sucursal_params
      params.require(:sucursal).permit(:nombre, :calle, :colonia, :numero_exterior, :numero_interior, :codigo_postal, :ciudad, :pais)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/views/empleados/_form.html.erb
<%= form_with(model: empleado, local: true) do |form| %>
  <% if empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
        <% empleado.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_completo %>
    <%= form.text_field :nombre_completo %>
  </div>

  <div class="field">
    <%= form.label :RFC %>
    <%= form.text_field :RFC %>
  </div>

  <div class="field">
    <%= form.label :puesto %>
    <%= form.text_field :puesto %>
  </div>

  <div class="field">
    <%= form.label :sucursal_id %>
    <%= form.text_field :sucursal_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editar Empleado</h1>
<br>
<%= form_for(@empleado) do |f| %>
  <div class="form-group">
    <%= f.label :nombre_completo %>
    <%= f.text_field :nombre_completo, class: 'form-control', required:'required' %>
  </div>
  <div class="form-group">
    <%= f.label :RFC %><br>
    <%= f.text_field :RFC, class: 'form-control', required:'required' %>
  </div>
  <div class="form-group">
    <%= f.label :puesto %><br>
    <%= f.text_field :puesto, class: 'form-control', required:'required' %>
  </div>
  <div class="form-group">
    <%= f.label :sucursal_id %><br>
    <select name="empleado[sucursal_id]" id="empleado_sucursal_id" class="form-control" required="required">
      <% @sucursals.each do |sucursal| %>
        <% if  sucursal.id == @empleado.sucursal_id %>
          <option value= "<%= sucursal.id %>" selected><%= sucursal.nombre %> </option>
        <% else %>
          <option value= "<%= sucursal.id %>"><%= sucursal.nombre %> </option>
        <% end %>
      <% end %>
    </select>
  </div>
  <p>
    <%= f.submit "Guardar", class: 'btn btn-success' %>
  </p>
<% end %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre completo</th>
      <th>Rfc</th>
      <th>Puesto</th>
      <th>Sucursal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.nombre_completo %></td>
        <td><%= empleado.RFC %></td>
        <td><%= empleado.puesto %></td>
        <td><%= empleado.sucursal_id %></td>
        <td><%= link_to 'Show', empleado %></td>
        <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<h1>Registro Empleado</h1>
<br>
<%= form_for(@empleado) do |f| %>
  <div class="form-group">
    <%= f.label :nombre_completo %>
    <%= f.text_field :nombre_completo, class: 'form-control' , required:'required'%>
   </div>
  <div class="form-group">
    <%= f.label :RFC %><br>
    <%= f.text_field :RFC, class: 'form-control'  , required:'required'%>
  </div>
  <div class="form-group">
    <%= f.label :puesto %><br>
    <%= f.text_field :puesto, class: 'form-control'  , required:'required'%>
  </div>
  <div class="form-group">
    <%= f.label :sucursal_id %><br>
    <select name="empleado[sucursal_id]" id="empleado_sucursal_id" class="form-control" required="required">
    <option value="" selected disabled hidden>Seleccionar</option>
    <% @sucursals.each do |sucursal| %>
      <option value= "<%= sucursal.id %>" ><%= sucursal.nombre %></option>
    <% end %>
    </select>
  </div>
  <p>
    <%= f.submit "Guardar", class: 'btn btn-success' %>
  </p>
<% end %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre completo:</strong>
  <%= @empleado.nombre_completo %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @empleado.RFC %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @empleado.puesto %>
</p>

<p>
  <strong>Sucursal:</strong>
  <%= @empleado.sucursal_id %>
</p>

<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>

app/views/home/index.html.erb
<h1>Inicio</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Empleados</th>
      <th scope="col" ></th>
    </tr>
  </thead>

  <tbody>
    <% @sucursals.each do |sucursal| %>
      <tr>
        <td><%= sucursal.nombre %></td>
        <td><%= @empleados.where(sucursal: sucursal ).count %></td>
        <td><%= link_to 'Editar', edit_sucursal_path(sucursal) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamenDocumentosDigitales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div>
      <% if signed_in? %>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Inicio', root_path  %></li>
              <li><%= link_to 'Registrar sucursal', new_sucursal_path %></li>
              <li><%= link_to 'Registrar Empleado', new_empleado_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out"></span> Salir
                <% end %>
              </li>
            </ul>
          </div>
        </nav>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/sucursals/_form.html.erb
<%= form_with(model: sucursal, local: true) do |form| %>
  <% if sucursal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sucursal.errors.count, "error") %> prohibited this sucursal from being saved:</h2>

      <ul>
        <% sucursal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :calle %>
    <%= form.text_field :calle %>
  </div>

  <div class="field">
    <%= form.label :colonia %>
    <%= form.text_field :colonia %>
  </div>

  <div class="field">
    <%= form.label :numero_exterior %>
    <%= form.text_field :numero_exterior %>
  </div>

  <div class="field">
    <%= form.label :numero_interior %>
    <%= form.text_field :numero_interior %>
  </div>

  <div class="field">
    <%= form.label :codigo_postal %>
    <%= form.number_field :codigo_postal %>
  </div>

  <div class="field">
    <%= form.label :ciudad %>
    <%= form.text_field :ciudad %>
  </div>

  <div class="field">
    <%= form.label :pais %>
    <%= form.text_field :pais %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sucursals/edit.html.erb
<h1>Editar Sucursal</h1>

<br>

<%= form_for(@sucursal) do |f| %>
  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, class: 'form-control' , required:'required'%>
   </div>
  <div class="form-group">
    <%= f.label :calle %><br>
    <%= f.text_field :calle, class: 'form-control'  , required:'required'%>
  </div>
  <div class="form-group">
    <%= f.label :colonia %><br>
    <%= f.text_field :colonia, class: 'form-control'  , required:'required'%>
  </div>
    <div class="form-group">
    <%= f.label :numero_exterior %><br>
    <%= f.text_field :numero_exterior, class: 'form-control'  , required:'required'%>
  </div>
      <div class="form-group">
    <%= f.label :numero_interior %><br>
    <%= f.text_field :numero_interior, class: 'form-control'  %>
  </div>
      <div class="form-group">
    <%= f.label :codigo_postal %><br>
    <%= f.text_field :codigo_postal, class: 'form-control'  , required:'required'%>
  </div>
        <div class="form-group">
    <%= f.label :pais %><br>
    <%= f.text_field :pais, class: 'form-control'  , required:'required'%>
  </div>
  <p>
    <%= f.submit "Guardar", class: 'btn btn-success' %>
  </p>
<% end %>

<h1>Empleados</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre completo</th>
      <th scope="col">RFC</th>
      <th scope="col" >Puesto</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.nombre_completo %></td>
        <td><%= empleado.RFC %></td>
        <td><%= empleado.puesto %></td>
        <td><%= link_to 'Editar', edit_empleado_path(empleado) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sucursals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sucursals</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Calle</th>
      <th>Colonia</th>
      <th>Numero exterior</th>
      <th>Numero interior</th>
      <th>Codigo postal</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sucursals.each do |sucursal| %>
      <tr>
        <td><%= sucursal.nombre %></td>
        <td><%= sucursal.calle %></td>
        <td><%= sucursal.colonia %></td>
        <td><%= sucursal.numero_exterior %></td>
        <td><%= sucursal.numero_interior %></td>
        <td><%= sucursal.codigo_postal %></td>
        <td><%= sucursal.ciudad %></td>
        <td><%= sucursal.pais %></td>
        <td><%= sucursal.user_id %></td>
        <td><%= link_to 'Show', sucursal %></td>
        <td><%= link_to 'Edit', edit_sucursal_path(sucursal) %></td>
        <td><%= link_to 'Destroy', sucursal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sucursal', new_sucursal_path %>

app/views/sucursals/new.html.erb
<h1>Registro Sucursal</h1>
<br>
<%= form_for(@sucursal) do |f| %>
  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, class: 'form-control', required:'required' %>
   </div>
  <div class="form-group">
    <%= f.label :calle %><br>
    <%= f.text_field :calle, class: 'form-control', required:'required'  %>
  </div>
  <div class="form-group">
    <%= f.label :colonia %><br>
    <%= f.text_field :colonia, class: 'form-control', required:'required' %>
  </div>
    <div class="form-group">
    <%= f.label :numero_exterior %><br>
    <%= f.text_field :numero_exterior, class: 'form-control', required:'required'%>
  </div>
      <div class="form-group">
    <%= f.label :numero_interior %><br>
    <%= f.text_field :numero_interior, class: 'form-control'  %>
  </div>
      <div class="form-group">
    <%= f.label :codigo_postal %><br>
    <%= f.text_field :codigo_postal, class: 'form-control' , required:'required'%>
  </div>
        <div class="form-group">
    <%= f.label :pais %><br>
    <%= f.text_field :pais, class: 'form-control'  %>
  </div>
  <p>
    <%= f.submit "Guardar", class: 'btn btn-success' %>
  </p>
<% end %>

app/views/sucursals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @sucursal.nombre %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @sucursal.calle %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @sucursal.colonia %>
</p>

<p>
  <strong>Numero exterior:</strong>
  <%= @sucursal.numero_exterior %>
</p>

<p>
  <strong>Numero interior:</strong>
  <%= @sucursal.numero_interior %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @sucursal.codigo_postal %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @sucursal.ciudad %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @sucursal.pais %>
</p>

<p>
  <strong>User:</strong>
  <%= @sucursal.user_id %>
</p>

<%= link_to 'Edit', edit_sucursal_path(@sucursal) %> |
<%= link_to 'Back', sucursals_path %>